/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PriceResponseDto
 */
export interface PriceResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PriceResponseDto
     */
    'price_id': number;
    /**
     * 
     * @type {number}
     * @memberof PriceResponseDto
     */
    'price_value': number;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseDto
     */
    'price_creation_time': string;
    /**
     * 
     * @type {number}
     * @memberof PriceResponseDto
     */
    'price_appuser_id': number;
}

