/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductUpdateDTO
 */
export interface ProductUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    'product_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    'product_description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateDTO
     */
    'product_appuser_id'?: number;
}

