/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PriceResponseDto } from './price-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductResponseDTO } from './product-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductWithPricesResponseDTO } from './product-with-prices-response-dto';

/**
 * @type StoreControllerGetStoreProducts200Response
 * @export
 */
export type StoreControllerGetStoreProducts200Response = ProductResponseDTO | ProductWithPricesResponseDTO;


