/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GeoPoint } from './geo-point';

/**
 * @type StoreResponseDTOStoreLocation
 * A GeoJSON point
 * @export
 */
export type StoreResponseDTOStoreLocation = GeoPoint;


