/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StoreCreateDTO
 */
export interface StoreCreateDTO {
    /**
     * 
     * @type {string}
     * @memberof StoreCreateDTO
     */
    'store_name': string;
    /**
     * 
     * @type {number}
     * @memberof StoreCreateDTO
     */
    'store_lat': number;
    /**
     * 
     * @type {number}
     * @memberof StoreCreateDTO
     */
    'store_lon': number;
    /**
     * 
     * @type {string}
     * @memberof StoreCreateDTO
     */
    'store_description': string;
    /**
     * 
     * @type {string}
     * @memberof StoreCreateDTO
     */
    'store_schedule'?: string;
    /**
     * 
     * @type {number}
     * @memberof StoreCreateDTO
     */
    'store_appuser_id': number;
}

