/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StoreUpdateDTO
 */
export interface StoreUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof StoreUpdateDTO
     */
    'store_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof StoreUpdateDTO
     */
    'store_lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof StoreUpdateDTO
     */
    'store_lon'?: number;
    /**
     * 
     * @type {string}
     * @memberof StoreUpdateDTO
     */
    'store_description'?: string;
    /**
     * 
     * @type {string}
     * @memberof StoreUpdateDTO
     */
    'store_schedule'?: string;
}

