/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StoreAssignProductDTO
 */
export interface StoreAssignProductDTO {
    /**
     * 
     * @type {number}
     * @memberof StoreAssignProductDTO
     */
    'product_availability'?: number;
}

