/* tslint:disable */
/* eslint-disable */
/**
 * APPriceit
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSearchDTO
 */
export interface UserSearchDTO {
    /**
     * 
     * @type {number}
     * @memberof UserSearchDTO
     */
    'appuser_id': number;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_name': string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_password': string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_creation_date': string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_email': string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_role': UserSearchDTOAppuserRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UserSearchDTO
     */
    'appuser_state': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSearchDTO
     */
    'appuser_refresh_token': string;
}

export const UserSearchDTOAppuserRoleEnum = {
    User: 'User',
    Mod: 'Mod',
    Admin: 'Admin'
} as const;

export type UserSearchDTOAppuserRoleEnum = typeof UserSearchDTOAppuserRoleEnum[keyof typeof UserSearchDTOAppuserRoleEnum];


